// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file HelloWorld.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace { char dummy; }
#endif

#include "HelloWorld.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

HelloWorld::HelloWorld()
{
    // m_instanceID com.eprosima.idl.parser.typecode.PrimitiveTypeCode@43d7741f
    m_instanceID = 0;
    // m_value com.eprosima.idl.parser.typecode.PrimitiveTypeCode@27fe3806
    m_value = 0.0;

}

HelloWorld::~HelloWorld()
{


}

HelloWorld::HelloWorld(const HelloWorld &x)
{
    m_instanceID = x.m_instanceID;
    m_value = x.m_value;
}

HelloWorld::HelloWorld(HelloWorld &&x)
{
    m_instanceID = x.m_instanceID;
    m_value = x.m_value;
}

HelloWorld& HelloWorld::operator=(const HelloWorld &x)
{

    m_instanceID = x.m_instanceID;
    m_value = x.m_value;

    return *this;
}

HelloWorld& HelloWorld::operator=(HelloWorld &&x)
{

    m_instanceID = x.m_instanceID;
    m_value = x.m_value;

    return *this;
}

size_t HelloWorld::getMaxCdrSerializedSize(size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);



    return current_alignment - initial_alignment;
}

size_t HelloWorld::getCdrSerializedSize(const HelloWorld& data, size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);



    return current_alignment - initial_alignment;
}

void HelloWorld::serialize(eprosima::fastcdr::Cdr &scdr) const
{

    scdr << m_instanceID;
    scdr << m_value;
}

void HelloWorld::deserialize(eprosima::fastcdr::Cdr &dcdr)
{

    dcdr >> m_instanceID;
    dcdr >> m_value;
}

/*!
 * @brief This function sets a value in member instanceID
 * @param _instanceID New value for member instanceID
 */
void HelloWorld::instanceID(int32_t _instanceID)
{
m_instanceID = _instanceID;
}

/*!
 * @brief This function returns the value of member instanceID
 * @return Value of member instanceID
 */
int32_t HelloWorld::instanceID() const
{
    return m_instanceID;
}

/*!
 * @brief This function returns a reference to member instanceID
 * @return Reference to member instanceID
 */
int32_t& HelloWorld::instanceID()
{
    return m_instanceID;
}

/*!
 * @brief This function sets a value in member value
 * @param _value New value for member value
 */
void HelloWorld::value(double _value)
{
m_value = _value;
}

/*!
 * @brief This function returns the value of member value
 * @return Value of member value
 */
double HelloWorld::value() const
{
    return m_value;
}

/*!
 * @brief This function returns a reference to member value
 * @return Reference to member value
 */
double& HelloWorld::value()
{
    return m_value;
}


size_t HelloWorld::getKeyMaxCdrSerializedSize(size_t current_alignment)
{
    size_t current_align = current_alignment;





    return current_align;
}

bool HelloWorld::isKeyDefined()
{
   return true;
}

void HelloWorld::serializeKey(eprosima::fastcdr::Cdr &scdr) const
{
    (void) scdr;
     
     
}
