// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file HelloWorld.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _HELLOWORLD_H_
#define _HELLOWORLD_H_

// TODO Poner en el contexto.

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif
#else
#define eProsima_user_DllExport
#endif

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(HelloWorld_SOURCE)
#define HelloWorld_DllAPI __declspec( dllexport )
#else
#define HelloWorld_DllAPI __declspec( dllimport )
#endif // HelloWorld_SOURCE
#else
#define HelloWorld_DllAPI
#endif
#else
#define HelloWorld_DllAPI
#endif // _WIN32

namespace eprosima
{
    namespace fastcdr
    {
        class Cdr;
    }
}


/*!
 * @brief This class represents the structure HelloWorlding defined by the user in the IDL file.
 * @ingroup HELLOWORLD
 */
class HelloWorlding
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport HelloWorlding();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~HelloWorlding();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object HelloWorlding that will be copied.
     */
    eProsima_user_DllExport HelloWorlding(const HelloWorlding &x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object HelloWorlding that will be copied.
     */
    eProsima_user_DllExport HelloWorlding(HelloWorlding &&x);

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object HelloWorlding that will be copied.
     */
    eProsima_user_DllExport HelloWorlding& operator=(const HelloWorlding &x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object HelloWorlding that will be copied.
     */
    eProsima_user_DllExport HelloWorlding& operator=(HelloWorlding &&x);

    /*!
     * @brief This function sets a value in member instanceID
     * @param _instanceID New value for member instanceID
     */
    eProsima_user_DllExport void instanceID(double _instanceID);

    /*!
     * @brief This function returns the value of member instanceID
     * @return Value of member instanceID
     */
    eProsima_user_DllExport double instanceID() const;

    /*!
     * @brief This function returns a reference to member instanceID
     * @return Reference to member instanceID
     */
    eProsima_user_DllExport double& instanceID();

    /*!
     * @brief This function sets a value in member value
     * @param _value New value for member value
     */
    eProsima_user_DllExport void value(double _value);

    /*!
     * @brief This function returns the value of member value
     * @return Value of member value
     */
    eProsima_user_DllExport double value() const;

    /*!
     * @brief This function returns a reference to member value
     * @return Reference to member value
     */
    eProsima_user_DllExport double& value();

    /*!
     * @brief This function copies the value in member arr
     * @param _arr New value to be copied in member arr
     */
    eProsima_user_DllExport void arr(const std::array<double, 8> &_arr);

    /*!
     * @brief This function moves the value in member arr
     * @param _arr New value to be moved in member arr
     */
    eProsima_user_DllExport void arr(std::array<double, 8> &&_arr);

    /*!
     * @brief This function returns a constant reference to member arr
     * @return Constant reference to member arr
     */
    eProsima_user_DllExport const std::array<double, 8>& arr() const;

    /*!
     * @brief This function returns a reference to member arr
     * @return Reference to member arr
     */
    eProsima_user_DllExport std::array<double, 8>& arr();

    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(const HelloWorlding& data, size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(eprosima::fastcdr::Cdr &cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(eprosima::fastcdr::Cdr &cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(eprosima::fastcdr::Cdr &cdr) const;

private:
    double m_instanceID;
    double m_value;
    std::array<double, 8> m_arr;
};

#endif // _HELLOWORLD_H_