#!/bin/bash

./build/publisherLoop_1 &
pid=$!
echo $pid
sleep 3s
./build/subscriberLoop_1
sleep 3s
kill -2 $pid
echo 1 is Done
sleep 30s

./build/publisherLoop_2 &
pid=$!
echo $pid
sleep 3s
./build/subscriberLoop_2
sleep 3s
kill -2 $pid
echo 2 is Done
sleep 30s

./build/publisherLoop_3 &
pid=$!
echo $pid
sleep 3s
./build/subscriberLoop_3
sleep 3s
kill -2 $pid
echo 3 is Done
sleep 30s

./build/publisherLoop_4 &
pid=$!
echo $pid
sleep 3s
./build/subscriberLoop_4
sleep 3s
kill -2 $pid
echo 4 is Done
sleep 30s

./build/publisherLoop_5 &
pid=$!
echo $pid
sleep 3s
./build/subscriberLoop_5
sleep 3s
kill -2 $pid
echo 5 is Done
sleep 30s

./build/publisherLoop_6 &
pid=$!
echo $pid
sleep 3s
./build/subscriberLoop_6
sleep 3s
kill -2 $pid
echo 6 is Done
sleep 30s