module TestDataType_Speed
{
  struct data
  {
    //double instanceID;
    //double msgNr;
    double arr[48000];
    //double arr[32000];
    //double arr[16000];
  };
  #pragma keylist data arr
};
